trigger:
- master  

pool:
  name: default
  demands: 
    - Agent.Name -equals azure-agent-deb

variables:
- group: sync-variables

steps:
- script: |
    cd ~/azure_repo_master/
    git clone --branch master git@azure-dos.s1.primo1.orch:PrimoCollection/Documentation/_git/Documentation.RU
    cd ~/azure_repo_master/Documentation.RU/
    git remote add github git@github.com:Gvardas/azure_test.git
    git push github master --force
  displayName: 'Sync Azure Repo to GitHub'
