trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git clone https://Gvardas:${{ secrets.GITHUB_TOKEN }}@github.com/Gvardas/azure_test.git
      cd azure_test
      git config user.email "toxacomp@yandex.ru"
      git config user.name "Gvardas"
      cp -R $(Build.SourcesDirectory)/* .
      git add . 
      git commit -m "Sync from Azure DevOps"
      git push origin main
