trigger:
- master  

pool:
  name: default
  demands: 
    - Agent.Name -equals azure-agent-deb

variables:
- group: sync-variables

steps:
- script: |
    cd ~/azure_repo_master/
    git clone ssh://azure-dos.s1.primo1.orch:22/PrimoCollection/Documentation/_git/Documentation.RU  
    cd ~/azure_repo_master/Documentation.RU/
    git checkout master
    git pull
    git remote add github git@github.com:timur-primorpa/PrimoRPA/Documentation.RU.git
    git commit -m "Automated sync from Azure DevOps"
    git push github master --force
  displayName: 'Sync Azure Repo to GitHub-test1'
