trigger:
- master  # Ветка, которую вы отслеживаете в Azure

pool:
  name: default
  demands: 
    - Agent.Name -equals azure-agent-deb

variables:
- group: sync-variables

steps:
- script: |
    git config --global user.email "toxacomp@yandex.ru"
    git config --global user.name "Gvardas"
    git clone https://Gvardas:${GITHUB_TOKEN}@github.com/Gvardas/azure_test.git
    cd azure_test
    git remote add azure https://${AZURE_TOKEN}@azure-dos.s1.primo1.orch/PrimoCollection/Documentation/_git/Documentation.RU
    git fetch azure
    git checkout azure/master  # Ветка в Azure, которую вы хотите копировать
    git push origin master  # Пушим изменения в GitHub в ветку master
  displayName: 'Sync Azure Repo to GitHub'
